version: '3.8'

services:
  redis:
    image: redis:7.4.2
    container_name: my-redis
    command: ["redis-server"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - GOSU_VERSION=1.17
      - REDIS_VERSION=7.4.2
      - REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-7.4.2.tar.gz
      - REDIS_DOWNLOAD_SHA=4ddebbf09061cbb589011786febdb34f29767dd7f89dbe712d2b68e808af6a1f
    restart: no
    networks:
      - redis-net

volumes:
  redis-data:

networks:
  redis-net:
    driver: bridge
